# Generated by Django 4.1.1 on 2022-09-27 11:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='((\\+98)|0)[.\\- ]?[0-9][.\\- ]?[0-9][.\\- ]?[0-9]')]),
        ),
    ]
