# Generated by Django 4.1.2 on 2022-10-17 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
