# Generated by Django 4.1.1 on 2022-09-27 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_link_view_delete_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='View',
        ),
    ]
