# Generated by Django 4.1.2 on 2022-10-16 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0005_remove_link_status_remove_link_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=256)),
                ('country', models.CharField(max_length=256)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shortener.link')),
            ],
        ),
    ]
