# Generated by Django 4.1.2 on 2022-10-16 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0007_location_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='country_code',
            field=models.CharField(default='IR', max_length=256),
            preserve_default=False,
        ),
    ]
